services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ayacoo\RedirectTab\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Form/*'
      - '../Classes/Event/*'